### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by Danimation2001** [Sn0wy-0wl/RhythmGE#5]
Hi, I just found this project and it seems like a really neat idea! It'd be super useful for a project I am working on right now but it doesn't seem like it has been updated for a good while and the current release version has a few issues that make it quite difficult to use in any real capacity.

Is this project abandoned? Are there any alternatives?

**Comment by MadL1me** [comment]
@Danimation2001 unfortunately, yes, the project no longer will be updated, for a lot of reasons, one of them, is that I moved from gamedev to data science/webdev. I'm sorry you have this problem, hope you'll find some solution as soon as possible.

I know only 2 alternatives, first one, if you work with unity, you can check out this [asset](https://assetstore.unity.com/packages/tools/audio/rhythm-timeline-190908). Second one, is similar tool as mine, you can find it in this [repo](https://github.com/setchi/NoteEditor). I hope I helped you at least a little bit, good luck with your project

**Comment by Danimation2001** [comment]
Damn shame. The only thing really holding back from using this is not being able to load an RBM back into the tool to continue work on mapping so I need to make a chart in pretty much one sitting. I'll check out those other tools you linked, thanks for the help.
